Feature/#29/develop
ajiwai-project/torichu pull request #46
Opened 2023-08-12 01:07 UTC by makky0620

2023-08-12 11:18 UTC, ta9ma0k commented on lib/domain/cost/tag.dart
> +  factory Tag._({required String id, required String value}) = _Tag;
valueをuniqueな値としてしまって良いと思うのでIDはいらないかも！

2023-08-12 11:25 UTC, ta9ma0k requested changes

2023-08-12 11:25 UTC, ta9ma0k commented on lib/domain/cost/tags.dart
> +    return Tags._(value: [...value, tag]);
valueをuniqueにした場合、同じvalueは追加されないと嬉しいかも

2023-08-12 11:26 UTC, ta9ma0k commented
> Tagの情報を別のBoxとして持たせるか悩んだけど、まぁCostの中に入れても良いかと思って作っちゃいました。

良いと思います！

2023-08-13 00:18 UTC, makky0620 commented
@ta9ma0k 修正しまいした

2023-08-13 11:23 UTC, ta9ma0k approved these changes

2023-08-13 12:13 UTC, ta9ma0k commented
@makky0620 
とても良い感じ🤩🤩🤩🤩🤩🤩

タグを一覧に表示すること、マイグレーションができることをまとめてリリースしたいのでマージするブランチを`release/1.1.0`にします！

2023-08-13 12:13 UTC, closed without merging